modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, Coco(几何)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.6.4, 2.10)"
    ordering="BEFORE"
    side="BOTH"
