modLoader="javafml"
loaderVersion="[33,)"
license="ARR"

[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, MalayP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""
license="ARR"

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.3, 3.9)"
    ordering="BEFORE"
    side="BOTH"
