modLoader="javafml"
loaderVersion="[37,)"
license="ARR"

[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee, WZD, MalayP"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description=""
license="ARR"

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[5, 6)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.fruittrees]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.59, )"
    ordering="BEFORE"
    side="BOTH"

[modproperties.fruittrees]
    catalogueItemIcon="fruittrees:grapefruit"
