modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="fruittrees"
version="${file.jarVersion}"
displayName="Fruit Trees"
authors="Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fruit-trees"
description='''Huge thanks to my supporters:

粉鱼 Lioness131 皮蛋 路人玖 Cherls idyllic_bean 鱼加盐有点咸 洋葱菜菜子 面条公爵 车轮饼 mc00zhu 洛华 纪华裕 可爱至吉 ycccz 东篱下i Ruriri Meowsquito
'''

[[dependencies.fruittrees]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.5.2, 2.9)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.fruittrees]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.16,)"
    ordering="BEFORE"
    side="BOTH"
